apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-cn-north4-cert-fluentd
  namespace: argocd
  labels:
    community: mindspore-cn-north4
spec:
  destination:
    namespace: kube-system
    server: https://114.115.223.130:5443
  project: infra-common
  source:
    path: common-applications/control/fluentd
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
