apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-cn-north4-ingress
  namespace: argocd
  labels:
    community: mindspore-cn-north4
spec:
  destination:
    namespace: ingress-nginx
    server: https://114.116.199.235:5443
  project: infra-common
  source:
    path: common-applications/mindspore-cn-north4/ingress
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
