apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openlookeng-website-ingress
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: openlookeng-website
    server: https://159.138.41.5:5443
  project: openeuler
  source:
    path: applications/openlookeng-website
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
