apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-package-manage
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: packagemanage
    server: https://159.138.41.5:5443
  project: openeuler
  source:
    path: applications/package-manage
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true