apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openeuler
  namespace: argocd
spec:
  description: The project that holds all of the business service used by openEuler community
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/opensourceways/infra-openeuler.git

