apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openeuler-hk-ssh-tunnel
  namespace: argocd
  labels:
    community: openeuler-hk
spec:
  destination:
    namespace: ssh-tunnel
    server: https://159.138.41.5:5443
  project: openeuler
  source:
    path: applications/ssh-tunnel
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD

