apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-jenkins
  namespace: argocd
  labels:
    community: os-infra
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: infra-common
  source:
    path: common-applications/control/jenkins
    repoURL: https://github.com/opensourceways/infra-common.git
    targetRevision: HEAD
