apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mindspore
  namespace: argocd
spec:
  description: The project that holds all of the business service used by MindSpore community
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://114.115.223.130:5443
    - namespace: '*'
      server: https://114.116.199.235:5443
    - namespace: '*'
      server: https://121.36.22.144:5443
  sourceRepos:
    - https://github.com/opensourceways/infra-mindspore.git
