apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-cn-north4-repo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    community: mindspore-cn-north4
spec:
  destination:
    namespace: download
    server: https://114.115.223.130:5443
  project: mindspore
  source:
    path: applications/repo
    repoURL: https://github.com/opensourceways/infra-mindspore.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
