apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-cn-north1-repo-tools
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    community: mindspore-cn-north1
spec:
  destination:
    namespace: repo-thridparty
    server: https://114.115.223.130:5443
  project: mindspore
  source:
    path: applications/tools
    repoURL: https://github.com/opensourceways/infra-mindspore.git
    targetRevision: HEAD