apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindspore-x86-slave
  namespace: argocd
  labels:
    community: mindspore-cn-north4
spec:
  destination:
    namespace: jenkins
    server: https://114.116.199.235:5443
  project: mindspore
  source:
    path: applications/jenkins-x86-slave
    repoURL: https://github.com/opensourceways/infra-mindspore.git
    targetRevision: HEAD
