apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch-jenkins
  namespace: argocd
  labels:
    community: pytorch
spec:
  destination:
    namespace: jenkins
    server: https://124.70.9.107:5443
  project: pytorch
  source:
    path: applications/jenkins
    repoURL: https://github.com/opensourceways/infra-pytorch.git
    targetRevision: HEAD
