apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openlookeng-jenkins-ingress
  namespace: argocd
  labels:
    community: openlookeng
spec:
  destination:
    namespace: openlookeng-jenkins
    server: https://159.138.41.5:5443
  project: openlookeng
  source:
    path: applications/openlookeng-jenkins
    repoURL: https://github.com/opensourceways/infra-openeuler.git
    targetRevision: HEAD

