apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openlookeng
  namespace: argocd
spec:
  description: The project that holds all of the business service used by openLookeng community
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://159.138.57.217:5443
  sourceRepos:
    - https://github.com/opensourceways/infra-openlookeng.git
