apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-common
  namespace: argocd
spec:
  description: The project that holds all of the common service used by different communities
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/opensourceways/infra-common.git
  syncWindows:
    - applications:
        - '*'
      clusters:
        - '*'
      namespaces:
        - '*'
      duration: 1h
      kind: allow
      manualSync: true
      schedule: '* 22 * * *'
